require 'rake/clean'

SRC_DIR = "src"
OBJ_DIR = "out"

Dir.glob('rake/*.rake.rb').each { |r| 
  require "#{File.dirname(__FILE__)}/#{r}"
}

directory OBJ_DIR
defaults = [OBJ_DIR]
Rake.application.tasks.each do |t|
  if t.name.match(/:default$/)
    defaults << t
  end
end

desc "Build the final morphology analysis FST."
task :morph => "out/morphology.a"

file "out/morphology.a" => defaults do
  sh "fst-compiler src/morphology.fst out/morphology.a"
end

desc "Build the final AT&T format FST required for Parsley."
task :att => "out/morphology.att"

file "out/morphology.att" => "out/morphology.a" do
  sh "fst-print out/morphology.a > out/morphology.att"
end

task :default => :att
